services:
  password-manager:
    build: .
    image: pm:dev
    container_name: password-manager
    environment:
      - DISPLAY=${DISPLAY_IP}:1
    volumes:
    - ./data:/app/data
    stdin_open: true
    tty: true